### ISSUE TITLE
I got a AttributeError

### ISSUE THREAD

**Issue by willhunger** [robobenklein/ubuntu-airplay#10]
`
Got systrayicon from settings:False
Got promptOnClose_systray from settings:False
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    window = Window()
  File "main.py", line 53, in __init__
    self.createTrayIcon()
  File "main.py", line 276, in createTrayIcon
    self.trayIconMenu.addAction(self.maximizeAction)
AttributeError: 'Window' object has no attribute 'maximizeAction'
`
How can i deal with this problem?(￣(エ)￣)ゞ

**Comment by willhunger** [comment]
Got systrayicon from settings:False
Got promptOnClose_systray from settings:False
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    window = Window()
  File "main.py", line 53, in __init__
    self.createTrayIcon()
  File "main.py", line 276, in createTrayIcon
    self.trayIconMenu.addAction(self.maximizeAction)
AttributeError: 'Window' object has no attribute 'maximizeAction'

**Comment by cadebrown** [comment]
@willhunger 
What version of Ubuntu are you running?

I too have this problem, and fixed it in https://github.com/CadeBrown/openairplay

I'll open a pull request

**Comment by willhunger** [comment]
@CadeBrown 
Great,fixed it.
I use Ubuntu 16.10
Thank you.
