### ISSUE TITLE
install.sh does not include python3-zeroconf

### ISSUE THREAD

**Issue by hackerb9** [robobenklein/ubuntu-airplay#14]
$ ./run.sh 
    python3 is /usr/bin/python3
    Debugging enabled.
    Called with system args: ['main.py']
    Python version: 3.5.3 (default, Jan 19 2017, 14:11:04) 
    [GCC 6.3.0 20170118]
    Python3 Zeroconf module could not be loaded.
    Please ensure you have it installed.
    Could not import own classes.
    Non-Zero exit status.
    Program quit.

`apt-get install python3-zeroconf` fixes the problem and should be added to install.sh.

(By the way, I very much like that your install.sh is simple enough that I can run each command by hand instead of executing it. And I appreciate that you're using the python3 libraries builtin to the system (using apt-get) instead of grabbing them from some third-party site.)

**Comment by robobenklein** [comment]
:+1:
