### ISSUE TITLE
How to stream, once the device is detected

### ISSUE THREAD

**Issue by windwalker78** [robobenklein/ubuntu-airplay#18]
Hi,

        Probably I'm not doing something correctly, but when I start the app, I see my device successfully discovered from linux Debian 10:

python3 is /usr/bin/python3
Debugging enabled.
Called with system args: ['main.py']
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
Got systrayicon from settings:True
Got promptOnClose_systray from settings:False
Starting discovery service...
Listener started.
Airplay receiver Mirascreen BFD9C7DD._airplay._tcp.local. added, service info: ServiceInfo(type='_airplay._tcp.local.', name='Mirascreen BFD9C7DD._airplay._tcp.local.', addresses=[b'\xc0\xa8+\x1b'], port=7000, weight=0, priority=0, server='Mirascreen BFD9C7DD.local.', properties={b'deviceid': b'D2:C0:BF:D9:C7:DD', b'features': b'0x0A7FEFF7,0x8', b'flags': b'0x4', b'rmodel': b'EZAir1,1', b'model': b'AppleTV3,2', b'srcvers': b'220.68', b'vv': b'2', b'pk': b'6eecbef4886bd4c68bea572913b497c210a2779de9ef05e8e505bd6e9a10a1d5', b'pi': b'b08f5a79-db29-4384-b456-a4784d9e6055'})
Adding device: Mirascreen BFD9C7DD._airplay._tcp.local.
Program returned to system tray, user chose not to be notified.
Closing to System Tray

I don't see any options in the GUI, which can help me in sharing my desktop. I see however AppleTV3.2, which seems like a recent version.

You feedback will be greatly appreciated.

Kind regards,
Todor

**Comment by robobenklein** [comment]
Can't really, lol...

There's no video code anywhere in this repo, when I abandoned the project the best it could do was send a JPG desktop screenshot each second to the airplay device. The way that worked was basically `while true; do <your-screenshot-program>; curl -XPUT -H 'X-Apple-AssetKey: <hash of photo>' -H 'User-Agent: MediaControl/1.0' -d '<jpg data>' '<ip>/photo'; done`, and you can run that without the need for this program assuming you know the IP and port.

**Comment by windwalker78** [comment]
Thank you very much for the explanation :)
